# 使用spring boot redis starter
spring:
  redis:
    host: xxx.xxx.xx.xxx # redis地址
    port: 6379  # redis端口
    password: xxxxxx # redis密码
    database: 0 # 库名
    client-type: lettuce # 2.x版本后，默认就是lettuce
    lettuce: # lettuce相关配置
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 2
    jedis:  # jedis相关配置
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲连接数
        min-idle: 2 # 最小空闲连接数